### ISSUE TITLE
listRooms - IE does not return more than 100 rooms

### ISSUE THREAD

**Issue by jamesm81** [bdm1981/Spark-Power-Pack#34]
working on listRooms and it all works fine in Chrome, Firefox, and Safari, but in IE, it will only pull the first 100 and not pull the remainder.  I'm using some of your code to pull the next link, but IE is not returning anything for the next link
nextlink = xhr.getResponseHeader('Link');
nextlink is coming back null for IE

because xhr.getResponseHeader('Link') is coming back as null

**Comment by bdm1981** [comment]
This is due to the headers coming back in an unsupported format. I have a case open with the spark dev team.

**Comment by bdm1981** [comment]
Apparently this is due to an IE limitation with CORS. We will have to implement something server side to resolve this. http://stackoverflow.com/questions/34696157/ie-misses-headers-angular-http
